// <auto-generated />
using System;
using MeetMe.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MeetMe.Service.Migrations
{
    [DbContext(typeof(MeetingsContext))]
    partial class MeetingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0-rc1.19456.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MeetMe.Domain.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MeetMe.Domain.Models.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MeetMe.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OidcIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OidcIdentifier")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeetMe.Domain.Models.Invitation", b =>
                {
                    b.HasOne("MeetMe.Domain.Models.Meeting", null)
                        .WithMany("Invitations")
                        .HasForeignKey("MeetingId");

                    b.HasOne("MeetMe.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("MeetMe.Domain.Models.Vote", "Votes", b1 =>
                        {
                            b1.Property<Guid>("InvitationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProposalId")
                                .HasColumnType("uuid");

                            b1.HasKey("InvitationId", "Id");

                            b1.ToTable("Vote");

                            b1.WithOwner()
                                .HasForeignKey("InvitationId");
                        });
                });

            modelBuilder.Entity("MeetMe.Domain.Models.Meeting", b =>
                {
                    b.HasOne("MeetMe.Domain.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.OwnsMany("MeetMe.Domain.Models.Proposal", "Proposals", b1 =>
                        {
                            b1.Property<Guid>("MeetingId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Time")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MeetingId", "Id");

                            b1.ToTable("Proposal");

                            b1.WithOwner()
                                .HasForeignKey("MeetingId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
